pub const EVEN: [&str; 256] = [
    "aardvark",
    "absurd",
    "accrue",
    "acme",
    "adrift",
    "adult",
    "afflict",
    "ahead",
    "aimless",
    "Algol",
    "allow",
    "alone",
    "ammo",
    "ancient",
    "apple",
    "artist",
    "assume",
    "Athens",
    "atlas",
    "Aztec",
    "baboon",
    "backfield",
    "backward",
    "banjo",
    "beaming",
    "bedlamp",
    "beehive",
    "beeswax",
    "befriend",
    "Belfast",
    "berserk",
    "billiard",
    "bison",
    "blackjack",
    "blockade",
    "blowtorch",
    "bluebird",
    "bombast",
    "bookshelf",
    "brackish",
    "breadline",
    "breakup",
    "brickyard",
    "briefcase",
    "Burbank",
    "button",
    "buzzard",
    "cement",
    "chairlift",
    "chatter",
    "checkup",
    "chisel",
    "choking",
    "chopper",
    "Christmas",
    "clamshell",
    "classic",
    "classroom",
    "cleanup",
    "clockwork",
    "cobra",
    "commence",
    "concert",
    "cowbell",
    "crackdown",
    "cranky",
    "crowfoot",
    "crucial",
    "crumpled",
    "crusade",
    "cubic",
    "dashboard",
    "deadbolt",
    "deckhand",
    "dogsled",
    "dragnet",
    "drainage",
    "dreadful",
    "drifter",
    "dropper",
    "drumbeat",
    "drunken",
    "Dupont",
    "dwelling",
    "eating",
    "edict",
    "egghead",
    "eightball",
    "endorse",
    "endow",
    "enlist",
    "erase",
    "escape",
    "exceed",
    "eyeglass",
    "eyetooth",
    "facial",
    "fallout",
    "flagpole",
    "flatfoot",
    "flytrap",
    "fracture",
    "framework",
    "freedom",
    "frighten",
    "gazelle",
    "Geiger",
    "glitter",
    "glucose",
    "goggles",
    "goldfish",
    "gremlin",
    "guidance",
    "hamlet",
    "highchair",
    "hockey",
    "indoors",
    "indulge",
    "inverse",
    "involve",
    "island",
    "jawbone",
    "keyboard",
    "kickoff",
    "kiwi",
    "klaxon",
    "locale",
    "lockup",
    "merit",
    "minnow",
    "miser",
    "Mohawk",
    "mural",
    "music",
    "necklace",
    "Neptune",
    "newborn",
    "nightbird",
    "Oakland",
    "obtuse",
    "offload",
    "optic",
    "orca",
    "payday",
    "peachy",
    "pheasant",
    "physique",
    "playhouse",
    "Pluto",
    "preclude",
    "prefer",
    "preshrunk",
    "printer",
    "prowler",
    "pupil",
    "puppy",
    "python",
    "quadrant",
    "quiver",
    "quota",
    "ragtime",
    "ratchet",
    "rebirth",
    "reform",
    "regain",
    "reindeer",
    "rematch",
    "repay",
    "retouch",
    "revenge",
    "reward",
    "rhythm",
    "ribcage",
    "ringbolt",
    "robust",
    "rocker",
    "ruffled",
    "sailboat",
    "sawdust",
    "scallion",
    "scenic",
    "scorecard",
    "Scotland",
    "seabird",
    "select",
    "sentence",
    "shadow",
    "shamrock",
    "showgirl",
    "skullcap",
    "skydive",
    "slingshot",
    "slowdown",
    "snapline",
    "snapshot",
    "snowcap",
    "snowslide",
    "solo",
    "southward",
    "soybean",
    "spaniel",
    "spearhead",
    "spellbind",
    "spheroid",
    "spigot",
    "spindle",
    "spyglass",
    "stagehand",
    "stagnate",
    "stairway",
    "standard",
    "stapler",
    "steamship",
    "sterling",
    "stockman",
    "stopwatch",
    "stormy",
    "sugar",
    "surmount",
    "suspense",
    "sweatband",
    "swelter",
    "tactics",
    "talon",
    "tapeworm",
    "tempest",
    "tiger",
    "tissue",
    "tonic",
    "topmost",
    "tracker",
    "transit",
    "trauma",
    "treadmill",
    "Trojan",
    "trouble",
    "tumor",
    "tunnel",
    "tycoon",
    "uncut",
    "unearth",
    "unwind",
    "uproot",
    "upset",
    "upshot",
    "vapor",
    "village",
    "virus",
    "Vulcan",
    "waffle",
    "wallet",
    "watchword",
    "wayside",
    "willow",
    "woodlark",
    "Zulu",
];

pub const ODD: [&str; 256] = [
    "adroitness",
    "adviser",
    "aftermath",
    "aggregate",
    "alkali",
    "almighty",
    "amulet",
    "amusement",
    "antenna",
    "applicant",
    "Apollo",
    "armistice",
    "article",
    "asteroid",
    "Atlantic",
    "atmosphere",
    "autopsy",
    "Babylon",
    "backwater",
    "barbecue",
    "belowground",
    "bifocals",
    "bodyguard",
    "bookseller",
    "borderline",
    "bottomless",
    "Bradbury",
    "bravado",
    "Brazilian",
    "breakaway",
    "Burlington",
    "businessman",
    "butterfat",
    "Camelot",
    "candidate",
    "cannonball",
    "Capricorn",
    "caravan",
    "caretaker",
    "celebrate",
    "cellulose",
    "certify",
    "chambermaid",
    "Cherokee",
    "Chicago",
    "clergyman",
    "coherence",
    "combustion",
    "commando",
    "company",
    "component",
    "concurrent",
    "confidence",
    "conformist",
    "congregate",
    "consensus",
    "consulting",
    "corporate",
    "corrosion",
    "councilman",
    "crossover",
    "crucifix",
    "cumbersome",
    "customer",
    "Dakota",
    "decadence",
    "December",
    "decimal",
    "designing",
    "detector",
    "detergent",
    "determine",
    "dictator",
    "dinosaur",
    "direction",
    "disable",
    "disbelief",
    "disruptive",
    "distortion",
    "document",
    "embezzle",
    "enchanting",
    "enrollment",
    "enterprise",
    "equation",
    "equipment",
    "escapade",
    "Eskimo",
    "everyday",
    "examine",
    "existence",
    "exodus",
    "fascinate",
    "filament",
    "finicky",
    "forever",
    "fortitude",
    "frequency",
    "gadgetry",
    "Galveston",
    "getaway",
    "glossary",
    "gossamer",
    "graduate",
    "gravity",
    "guitarist",
    "hamburger",
    "Hamilton",
    "handiwork",
    "hazardous",
    "headwaters",
    "hemisphere",
    "hesitate",
    "hideaway",
    "holiness",
    "hurricane",
    "hydraulic",
    "impartial",
    "impetus",
    "inception",
    "indigo",
    "inertia",
    "infancy",
    "inferno",
    "informant",
    "insincere",
    "insurgent",
    "integrate",
    "intention",
    "inventive",
    "Istanbul",
    "Jamaica",
    "Jupiter",
    "leprosy",
    "letterhead",
    "liberty",
    "maritime",
    "matchmaker",
    "maverick",
    "Medusa",
    "megaton",
    "microscope",
    "microwave",
    "midsummer",
    "millionaire",
    "miracle",
    "misnomer",
    "molasses",
    "molecule",
    "Montana",
    "monument",
    "mosquito",
    "narrative",
    "nebula",
    "newsletter",
    "Norwegian",
    "October",
    "Ohio",
    "onlooker",
    "opulent",
    "Orlando",
    "outfielder",
    "Pacific",
    "pandemic",
    "Pandora",
    "paperweight",
    "paragon",
    "paragraph",
    "paramount",
    "passenger",
    "pedigree",
    "Pegasus",
    "penetrate",
    "perceptive",
    "performance",
    "pharmacy",
    "phonetic",
    "photograph",
    "pioneer",
    "pocketful",
    "politeness",
    "positive",
    "potato",
    "processor",
    "provincial",
    "proximate",
    "puberty",
    "publisher",
    "pyramid",
    "quantity",
    "racketeer",
    "rebellion",
    "recipe",
    "recover",
    "repellent",
    "replica",
    "reproduce",
    "resistor",
    "responsive",
    "retraction",
    "retrieval",
    "retrospect",
    "revenue",
    "revival",
    "revolver",
    "sandalwood",
    "sardonic",
    "Saturday",
    "savagery",
    "scavenger",
    "sensation",
    "sociable",
    "souvenir",
    "specialist",
    "speculate",
    "stethoscope",
    "stupendous",
    "supportive",
    "surrender",
    "suspicious",
    "sympathy",
    "tambourine",
    "telephone",
    "therapist",
    "tobacco",
    "tolerance",
    "tomorrow",
    "torpedo",
    "tradition",
    "travesty",
    "trombonist",
    "truncated",
    "typewriter",
    "ultimate",
    "undaunted",
    "underfoot",
    "unicorn",
    "unify",
    "universe",
    "unravel",
    "upcoming",
    "vacancy",
    "vagabond",
    "vertigo",
    "Virginia",
    "visitor",
    "vocalist",
    "voyager",
    "warranty",
    "Waterloo",
    "whimsical",
    "Wichita",
    "Wilmington",
    "Wyoming",
    "yesteryear",
    "Yucatan",
];

#[allow(clippy::unreadable_literal)]
pub static ODD_LOOKUP_LOWERCASE: phf::Map<&'static str, u8> = ::phf::Map {
    key: 732231254413039614,
    disps: ::phf::Slice::Static(&[
        (0, 5),
        (0, 41),
        (0, 87),
        (0, 24),
        (0, 35),
        (0, 4),
        (0, 10),
        (0, 36),
        (0, 0),
        (0, 2),
        (0, 53),
        (0, 0),
        (0, 80),
        (0, 11),
        (0, 153),
        (2, 1),
        (0, 69),
        (0, 23),
        (0, 0),
        (0, 25),
        (1, 67),
        (0, 6),
        (1, 107),
        (1, 0),
        (0, 55),
        (0, 203),
        (1, 101),
        (1, 209),
        (4, 72),
        (0, 52),
        (1, 60),
        (0, 39),
        (0, 96),
        (0, 44),
        (2, 164),
        (2, 0),
        (7, 121),
        (0, 4),
        (0, 84),
        (1, 0),
        (0, 14),
        (10, 197),
        (0, 24),
        (0, 58),
        (0, 1),
        (0, 5),
        (0, 215),
        (21, 135),
        (5, 175),
        (2, 4),
        (13, 83),
        (37, 40),
    ]),
    entries: ::phf::Slice::Static(&[
        ("medusa", 0x8b),
        ("enchanting", 0x51),
        ("stethoscope", 0xd7),
        ("fortitude", 0x60),
        ("alkali", 0x04),
        ("hazardous", 0x6d),
        ("concurrent", 0x33),
        ("embezzle", 0x50),
        ("pharmacy", 0xaf),
        ("disbelief", 0x4c),
        ("decimal", 0x43),
        ("upcoming", 0xf0),
        ("universe", 0xee),
        ("truncated", 0xe7),
        ("politeness", 0xb4),
        ("determine", 0x47),
        ("specialist", 0xd5),
        ("crossover", 0x3c),
        ("component", 0x32),
        ("wichita", 0xfb),
        ("istanbul", 0x82),
        ("recover", 0xc1),
        ("infancy", 0x7a),
        ("consulting", 0x38),
        ("bookseller", 0x17),
        ("wyoming", 0xfd),
        ("tolerance", 0xe1),
        ("atmosphere", 0x0f),
        ("clergyman", 0x2d),
        ("voyager", 0xf7),
        ("october", 0x9c),
        ("wilmington", 0xfc),
        ("holiness", 0x72),
        ("december", 0x42),
        ("pyramid", 0xbc),
        ("savagery", 0xd0),
        ("dinosaur", 0x49),
        ("fascinate", 0x5c),
        ("finicky", 0x5e),
        ("rebellion", 0xbf),
        ("equipment", 0x55),
        ("equation", 0x54),
        ("misnomer", 0x92),
        ("sardonic", 0xce),
        ("cannonball", 0x23),
        ("liberty", 0x87),
        ("trombonist", 0xe6),
        ("revolver", 0xcc),
        ("adroitness", 0x00),
        ("gravity", 0x68),
        ("certify", 0x29),
        ("hydraulic", 0x74),
        ("consensus", 0x37),
        ("unicorn", 0xec),
        ("customer", 0x3f),
        ("intention", 0x80),
        ("article", 0x0c),
        ("passenger", 0xa9),
        ("camelot", 0x21),
        ("provincial", 0xb8),
        ("undaunted", 0xea),
        ("capricorn", 0x24),
        ("jamaica", 0x83),
        ("vocalist", 0xf6),
        ("monument", 0x96),
        ("combustion", 0x2f),
        ("conformist", 0x35),
        ("typewriter", 0xe8),
        ("aggregate", 0x03),
        ("brazilian", 0x1c),
        ("exodus", 0x5b),
        ("amulet", 0x06),
        ("distortion", 0x4e),
        ("penetrate", 0xac),
        ("guitarist", 0x69),
        ("pioneer", 0xb2),
        ("congregate", 0x36),
        ("retraction", 0xc7),
        ("atlantic", 0x0e),
        ("outfielder", 0xa1),
        ("sociable", 0xd3),
        ("quantity", 0xbd),
        ("disruptive", 0x4d),
        ("celebrate", 0x27),
        ("pandora", 0xa4),
        ("filament", 0x5d),
        ("chambermaid", 0x2a),
        ("impetus", 0x76),
        ("tambourine", 0xdd),
        ("gadgetry", 0x62),
        ("retrieval", 0xc8),
        ("inventive", 0x81),
        ("torpedo", 0xe3),
        ("surrender", 0xda),
        ("molasses", 0x93),
        ("document", 0x4f),
        ("hemisphere", 0x6f),
        ("detector", 0x45),
        ("adviser", 0x01),
        ("molecule", 0x94),
        ("amusement", 0x07),
        ("responsive", 0xc6),
        ("visitor", 0xf5),
        ("caretaker", 0x26),
        ("handiwork", 0x6c),
        ("bodyguard", 0x16),
        ("stupendous", 0xd8),
        ("performance", 0xae),
        ("norwegian", 0x9b),
        ("paramount", 0xa8),
        ("vacancy", 0xf1),
        ("paragraph", 0xa7),
        ("perceptive", 0xad),
        ("newsletter", 0x9a),
        ("microscope", 0x8d),
        ("opulent", 0x9f),
        ("paragon", 0xa6),
        ("dictator", 0x48),
        ("racketeer", 0xbe),
        ("microwave", 0x8e),
        ("pedigree", 0xaa),
        ("matchmaker", 0x89),
        ("backwater", 0x12),
        ("suspicious", 0xdb),
        ("ultimate", 0xe9),
        ("insincere", 0x7d),
        ("souvenir", 0xd4),
        ("informant", 0x7c),
        ("vagabond", 0xf2),
        ("warranty", 0xf8),
        ("applicant", 0x09),
        ("maverick", 0x8a),
        ("armistice", 0x0b),
        ("bradbury", 0x1a),
        ("telephone", 0xde),
        ("belowground", 0x14),
        ("orlando", 0xa0),
        ("pacific", 0xa2),
        ("revival", 0xcb),
        ("yesteryear", 0xfe),
        ("montana", 0x95),
        ("frequency", 0x61),
        ("corrosion", 0x3a),
        ("underfoot", 0xeb),
        ("decadence", 0x41),
        ("phonetic", 0xb0),
        ("vertigo", 0xf3),
        ("speculate", 0xd6),
        ("dakota", 0x40),
        ("impartial", 0x75),
        ("replica", 0xc3),
        ("whimsical", 0xfa),
        ("insurgent", 0x7e),
        ("hamilton", 0x6b),
        ("ohio", 0x9d),
        ("apollo", 0x0a),
        ("mosquito", 0x97),
        ("sandalwood", 0xcd),
        ("potato", 0xb6),
        ("leprosy", 0x85),
        ("retrospect", 0xc9),
        ("almighty", 0x05),
        ("commando", 0x30),
        ("paperweight", 0xa5),
        ("asteroid", 0x0d),
        ("examine", 0x59),
        ("tomorrow", 0xe2),
        ("galveston", 0x63),
        ("cumbersome", 0x3e),
        ("forever", 0x5f),
        ("coherence", 0x2e),
        ("hesitate", 0x70),
        ("onlooker", 0x9e),
        ("babylon", 0x11),
        ("bottomless", 0x19),
        ("burlington", 0x1e),
        ("graduate", 0x67),
        ("letterhead", 0x86),
        ("recipe", 0xc0),
        ("existence", 0x5a),
        ("corporate", 0x39),
        ("scavenger", 0xd1),
        ("detergent", 0x46),
        ("unravel", 0xef),
        ("cherokee", 0x2b),
        ("bifocals", 0x15),
        ("unify", 0xed),
        ("narrative", 0x98),
        ("glossary", 0x65),
        ("pegasus", 0xab),
        ("waterloo", 0xf9),
        ("getaway", 0x64),
        ("reproduce", 0xc4),
        ("repellent", 0xc2),
        ("antenna", 0x08),
        ("eskimo", 0x57),
        ("pocketful", 0xb3),
        ("hideaway", 0x71),
        ("processor", 0xb7),
        ("megaton", 0x8c),
        ("caravan", 0x25),
        ("inferno", 0x7b),
        ("designing", 0x44),
        ("sympathy", 0xdc),
        ("resistor", 0xc5),
        ("enterprise", 0x53),
        ("pandemic", 0xa3),
        ("cellulose", 0x28),
        ("aftermath", 0x02),
        ("maritime", 0x88),
        ("escapade", 0x56),
        ("supportive", 0xd9),
        ("indigo", 0x78),
        ("travesty", 0xe5),
        ("company", 0x31),
        ("headwaters", 0x6e),
        ("everyday", 0x58),
        ("inception", 0x77),
        ("borderline", 0x18),
        ("proximate", 0xb9),
        ("candidate", 0x22),
        ("autopsy", 0x10),
        ("hurricane", 0x73),
        ("gossamer", 0x66),
        ("hamburger", 0x6a),
        ("revenue", 0xca),
        ("inertia", 0x79),
        ("disable", 0x4b),
        ("miracle", 0x91),
        ("bravado", 0x1b),
        ("tobacco", 0xe0),
        ("millionaire", 0x90),
        ("nebula", 0x99),
        ("butterfat", 0x20),
        ("direction", 0x4a),
        ("chicago", 0x2c),
        ("therapist", 0xdf),
        ("yucatan", 0xff),
        ("tradition", 0xe4),
        ("sensation", 0xd2),
        ("puberty", 0xba),
        ("virginia", 0xf4),
        ("breakaway", 0x1d),
        ("positive", 0xb5),
        ("publisher", 0xbb),
        ("saturday", 0xcf),
        ("crucifix", 0x3d),
        ("enrollment", 0x52),
        ("councilman", 0x3b),
        ("midsummer", 0x8f),
        ("barbecue", 0x13),
        ("businessman", 0x1f),
        ("jupiter", 0x84),
        ("photograph", 0xb1),
        ("confidence", 0x34),
        ("integrate", 0x7f),
    ]),
};

#[allow(clippy::unreadable_literal)]
pub static EVEN_LOOKUP_LOWERCASE: phf::Map<&'static str, u8> = ::phf::Map {
    key: 3213172566270843353,
    disps: ::phf::Slice::Static(&[
        (1, 232),
        (0, 4),
        (0, 17),
        (0, 18),
        (0, 1),
        (0, 4),
        (0, 63),
        (1, 51),
        (0, 0),
        (0, 42),
        (0, 108),
        (1, 70),
        (0, 7),
        (0, 52),
        (0, 3),
        (0, 0),
        (0, 228),
        (5, 137),
        (0, 3),
        (0, 0),
        (33, 2),
        (0, 66),
        (0, 42),
        (0, 2),
        (0, 70),
        (11, 89),
        (1, 222),
        (0, 49),
        (5, 251),
        (0, 18),
        (0, 0),
        (0, 112),
        (1, 58),
        (0, 0),
        (2, 73),
        (1, 11),
        (1, 21),
        (8, 209),
        (45, 62),
        (2, 191),
        (20, 122),
        (0, 10),
        (0, 0),
        (0, 153),
        (45, 49),
        (0, 11),
        (0, 18),
        (1, 191),
        (0, 7),
        (1, 194),
        (14, 124),
        (40, 140),
    ]),
    entries: ::phf::Slice::Static(&[
        ("select", 0xb8),
        ("willow", 0xfd),
        ("snapshot", 0xc2),
        ("cobra", 0x3c),
        ("ragtime", 0xa0),
        ("slingshot", 0xbf),
        ("scenic", 0xb4),
        ("cranky", 0x41),
        ("glucose", 0x6c),
        ("drunken", 0x51),
        ("shamrock", 0xbb),
        ("solo", 0xc5),
        ("hockey", 0x73),
        ("breakup", 0x29),
        ("dragnet", 0x4b),
        ("retouch", 0xa8),
        ("spyglass", 0xce),
        ("cement", 0x2f),
        ("afflict", 0x06),
        ("freedom", 0x67),
        ("peachy", 0x90),
        ("reward", 0xaa),
        ("crucial", 0x43),
        ("quadrant", 0x9d),
        ("sterling", 0xd5),
        ("regain", 0xa4),
        ("dashboard", 0x47),
        ("stockman", 0xd6),
        ("baboon", 0x14),
        ("eyeglass", 0x5e),
        ("surmount", 0xda),
        ("tonic", 0xe4),
        ("pluto", 0x94),
        ("clockwork", 0x3b),
        ("flagpole", 0x62),
        ("tracker", 0xe6),
        ("prowler", 0x99),
        ("dupont", 0x52),
        ("topmost", 0xe5),
        ("ruffled", 0xb0),
        ("sweatband", 0xdc),
        ("stagehand", 0xcf),
        ("minnow", 0x81),
        ("gazelle", 0x69),
        ("athens", 0x11),
        ("crumpled", 0x44),
        ("eightball", 0x57),
        ("endow", 0x59),
        ("tactics", 0xde),
        ("uncut", 0xef),
        ("endorse", 0x58),
        ("woodlark", 0xfe),
        ("geiger", 0x6a),
        ("dropper", 0x4f),
        ("bedlamp", 0x19),
        ("assume", 0x10),
        ("highchair", 0x72),
        ("spigot", 0xcc),
        ("southward", 0xc6),
        ("absurd", 0x01),
        ("accrue", 0x02),
        ("keyboard", 0x7a),
        ("blackjack", 0x21),
        ("billiard", 0x1f),
        ("spindle", 0xcd),
        ("printer", 0x98),
        ("bombast", 0x25),
        ("banjo", 0x17),
        ("quiver", 0x9e),
        ("trojan", 0xea),
        ("treadmill", 0xe9),
        ("python", 0x9c),
        ("belfast", 0x1d),
        ("button", 0x2d),
        ("wayside", 0xfc),
        ("preshrunk", 0x97),
        ("tissue", 0xe3),
        ("crusade", 0x45),
        ("ringbolt", 0xad),
        ("trouble", 0xeb),
        ("escape", 0x5c),
        ("aztec", 0x13),
        ("sugar", 0xd9),
        ("tumor", 0xec),
        ("ahead", 0x07),
        ("blockade", 0x22),
        ("flatfoot", 0x63),
        ("uproot", 0xf2),
        ("snowslide", 0xc4),
        ("goggles", 0x6d),
        ("tempest", 0xe1),
        ("island", 0x78),
        ("sentence", 0xb9),
        ("jawbone", 0x79),
        ("kickoff", 0x7b),
        ("pheasant", 0x91),
        ("erase", 0x5b),
        ("swelter", 0xdd),
        ("scallion", 0xb3),
        ("robust", 0xae),
        ("facial", 0x60),
        ("algol", 0x09),
        ("dreadful", 0x4d),
        ("buzzard", 0x2e),
        ("tycoon", 0xee),
        ("rebirth", 0xa2),
        ("showgirl", 0xbc),
        ("cleanup", 0x3a),
        ("standard", 0xd2),
        ("spheroid", 0xcb),
        ("crowfoot", 0x42),
        ("ancient", 0x0d),
        ("sailboat", 0xb1),
        ("reindeer", 0xa5),
        ("classic", 0x38),
        ("indoors", 0x74),
        ("pupil", 0x9a),
        ("trauma", 0xe8),
        ("alone", 0x0b),
        ("spaniel", 0xc8),
        ("adrift", 0x04),
        ("involve", 0x77),
        ("vulcan", 0xf8),
        ("snapline", 0xc1),
        ("checkup", 0x32),
        ("drifter", 0x4e),
        ("locale", 0x7e),
        ("zulu", 0xff),
        ("framework", 0x66),
        ("indulge", 0x75),
        ("chopper", 0x35),
        ("offload", 0x8c),
        ("miser", 0x82),
        ("blowtorch", 0x23),
        ("rematch", 0xa6),
        ("fracture", 0x65),
        ("chairlift", 0x30),
        ("apple", 0x0e),
        ("beeswax", 0x1b),
        ("quota", 0x9f),
        ("backfield", 0x15),
        ("upset", 0xf3),
        ("steamship", 0xd4),
        ("rocker", 0xaf),
        ("eating", 0x54),
        ("egghead", 0x56),
        ("skullcap", 0xbd),
        ("acme", 0x03),
        ("village", 0xf6),
        ("drumbeat", 0x50),
        ("chisel", 0x33),
        ("bluebird", 0x24),
        ("breadline", 0x28),
        ("neptune", 0x87),
        ("talon", 0xdf),
        ("stapler", 0xd3),
        ("upshot", 0xf4),
        ("stopwatch", 0xd7),
        ("ratchet", 0xa1),
        ("watchword", 0xfb),
        ("glitter", 0x6b),
        ("goldfish", 0x6e),
        ("klaxon", 0x7d),
        ("lockup", 0x7f),
        ("bison", 0x20),
        ("flytrap", 0x64),
        ("orca", 0x8e),
        ("newborn", 0x88),
        ("payday", 0x8f),
        ("drainage", 0x4c),
        ("unwind", 0xf1),
        ("spellbind", 0xca),
        ("briefcase", 0x2b),
        ("bookshelf", 0x26),
        ("revenge", 0xa9),
        ("scorecard", 0xb5),
        ("gremlin", 0x6f),
        ("burbank", 0x2c),
        ("sawdust", 0xb2),
        ("transit", 0xe7),
        ("obtuse", 0x8b),
        ("optic", 0x8d),
        ("enlist", 0x5a),
        ("aimless", 0x08),
        ("christmas", 0x36),
        ("cowbell", 0x3f),
        ("befriend", 0x1c),
        ("inverse", 0x76),
        ("wallet", 0xfa),
        ("merit", 0x80),
        ("berserk", 0x1e),
        ("snowcap", 0xc3),
        ("frighten", 0x68),
        ("stairway", 0xd1),
        ("tapeworm", 0xe0),
        ("ammo", 0x0c),
        ("brickyard", 0x2a),
        ("edict", 0x55),
        ("suspense", 0xdb),
        ("mohawk", 0x83),
        ("clamshell", 0x37),
        ("skydive", 0xbe),
        ("atlas", 0x12),
        ("tunnel", 0xed),
        ("hamlet", 0x71),
        ("dogsled", 0x4a),
        ("crackdown", 0x40),
        ("rhythm", 0xab),
        ("puppy", 0x9b),
        ("concert", 0x3e),
        ("seabird", 0xb7),
        ("nightbird", 0x89),
        ("repay", 0xa7),
        ("soybean", 0xc7),
        ("eyetooth", 0x5f),
        ("backward", 0x16),
        ("chatter", 0x31),
        ("physique", 0x92),
        ("ribcage", 0xac),
        ("fallout", 0x61),
        ("adult", 0x05),
        ("cubic", 0x46),
        ("spearhead", 0xc9),
        ("playhouse", 0x93),
        ("music", 0x85),
        ("scotland", 0xb6),
        ("reform", 0xa3),
        ("aardvark", 0x00),
        ("virus", 0xf7),
        ("shadow", 0xba),
        ("beehive", 0x1a),
        ("deckhand", 0x49),
        ("deadbolt", 0x48),
        ("tiger", 0xe2),
        ("dwelling", 0x53),
        ("slowdown", 0xc0),
        ("preclude", 0x95),
        ("necklace", 0x86),
        ("vapor", 0xf5),
        ("choking", 0x34),
        ("stagnate", 0xd0),
        ("commence", 0x3d),
        ("brackish", 0x27),
        ("beaming", 0x18),
        ("waffle", 0xf9),
        ("kiwi", 0x7c),
        ("exceed", 0x5d),
        ("mural", 0x84),
        ("oakland", 0x8a),
        ("guidance", 0x70),
        ("prefer", 0x96),
        ("unearth", 0xf0),
        ("artist", 0x0f),
        ("allow", 0x0a),
        ("classroom", 0x39),
        ("stormy", 0xd8),
    ]),
};
